# Generated by Django 5.0.3 on 2026-09-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSourceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Relative file path within repository', max_length=500)),
                ('language', models.CharField(default='python', max_length=50)),
                ('content', models.TextField(help_text='Raw source code content')),
                ('line_count', models.IntegerField(default=0)),
                ('file_size', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_codes', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='CodeSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('name', models.CharField(help_text='Function or Class name', max_length=255)),
                ('segment_type', models.CharField(choices=[('function', 'Function / Method'), ('class', 'Class / Module'), ('endpoint', 'API Endpoint Route'), ('general', 'Logical Code Block')], default='function', max_length=30)),
                ('docstring', models.TextField(blank=True, default='')),
                ('code_content', models.TextField()),
                ('signature', models.CharField(blank=True, default='', max_length=500)),
                ('start_line', models.IntegerField(default=1)),
                ('end_line', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_segments', to='projects.project')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='projects.projectsourcecode')),
            ],
        ),
    ]
