# Generated by Django 5.0.3 on 2026-08-26 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('similarity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_saved', models.IntegerField(default=160)),
                ('hourly_rate', models.IntegerField(default=1600)),
                ('cost_saved', models.BigIntegerField(default=256000)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('code', 'Code / Service Reuse'), ('api', 'REST / GraphQL API Reuse'), ('database', 'Database Schema / Vector Index'), ('ui', 'UI Component Library'), ('documentation', 'Architecture Design & Docs'), ('expertise', 'Team Consultation')], default='code', max_length=30)),
                ('description', models.TextField()),
                ('evidence', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('similarity_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='similarity.similarityresult')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('savings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.costsavings')),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='approvals.recommendation')),
            ],
        ),
    ]
