# Generated by Django 5.0.3 on 2026-08-26 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.IntegerField(help_text='Similarity percentage between 0 and 100')),
                ('similarity_level', models.CharField(choices=[('high', 'High Similarity (>80%)'), ('medium', 'Medium Similarity (60-80%)'), ('partial', 'Partial Component Match (40-60%)'), ('low', 'Low / Unique (<40%)')], default='medium', max_length=20)),
                ('matched_technologies', models.JSONField(default=list)),
                ('matched_concepts', models.JSONField(default=list)),
                ('llm_explanation', models.TextField(help_text='RAG-synthesized explanation of architectural overlap')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('similar_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_targets', to='projects.project')),
                ('source_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_sources', to='projects.project')),
            ],
        ),
    ]
